version: '3.8'
services:
  db:
    image: postgres:15rc1-alpine3.16
    container_name: patients_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql/data

  patients_app:
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя докерфайла из которого будет собран образ
      dockerfile: Dockerfile
      args:
        SERVER_PORT: 8500
        SERVER_HOST: localhost
    environment:
      - JDBC_URL=jdbc:postgresql://patients_db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=12345678
      - PORT=3500
    ports:
      - '8500:3500'
    networks:
      - backend
    depends_on:
      - db

volumes:
  db:
    driver: local

networks:
  backend: {}
