apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-app-deployment
  labels:
    app: patients-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patients-app
  template:
    metadata:
      labels:
        app: patients-app
    spec:
      containers:
      - name: patients-app
        image: vial0ft/ouch-it-hurts-app:p-93
        ports:
        - containerPort: 3500
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-port
        - name: PORT
          value: "3500"
---
apiVersion: v1
kind: Service
metadata:
  name: patients-app-service
spec:
  type: NodePort
  selector:
    app: patients-app
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 3500
      nodePort: 30111
