apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim0
  labels:
    app: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
