name: Test and publish docker image

on:
  push:
    branches: [ "main" ]

jobs:
  tests-and-publish-docker:
    steps:
    - uses: actions/checkout@v3
    - name: Build and deploy Docker image
      id: deploy
      uses: ./.github/actions/docker
      with:
        backend-server-address: ${{secrets.SERVER}}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

